import type { Metadata } from "next";
import { DM_Sans} from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const DMSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sass-Landing-Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(DMSans.className , "antialiased")}>{children}</body>
    </html>
  );
}
